name: Build Wyam and deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Setup .NET Core 3.1.101
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: 3.1.101

      - name: Setup .NET Core 2.1.803
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.803

      - name: Install Wyam Tool and Build
        run: |
          dotnet tool install -g wyam.tool
          wyam build

      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v1.0.1
        with:
          # Auth token to use with netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          # Your Netlify site id
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          # A deploy message
          NETLIFY_DEPLOY_MESSAGE: Deployed from master
          # Directory where built files are stored
          build_directory: output
