name: Build Wyam and deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .Net Core by script
        run: |
          wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          yes | sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update -y
          sudo apt-get install apt-transport-https -y
          sudo apt-get update -y
          sudo apt-get install dotnet-sdk-3.1 -y

#      - name: Setup .NET Core 3.1.101
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: 3.1.101

      - name: Install Wyam Tool
        run: dotnet tool restore

      - name: Build
        run: dotnet tool run wyam build

      - name: Netlify Deploy
        uses: jsmrcaga/action-netlify-deploy@v1.0.1
        with:
          # Auth token to use with netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          # Your Netlify site id
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          # A deploy message
          NETLIFY_DEPLOY_MESSAGE: Deployed from master
          # Directory where built files are stored
          build_directory: output
