name: Build Wyam and deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .Net Core by script
        run: |
          wget -q https://packages.microsoft.com/config/ubuntu/19.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          yes | sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update -y
          sudo apt-get install apt-transport-https -y
          sudo apt-get update -y
          sudo apt-get install dotnet-sdk-3.1 -y

      - name: Install Wyam Tool
        run: dotnet tool restore

      - name: Build
        run: dotnet tool run wyam build

      - name: Create Zip
        uses: TheDoctor0/zip-release@v0.2.1
        with:
        filename: output.zip
        path: output

      - name: Netlify Deploy
        run: "curl -H 'Authorization: Bearer ${{ secrets.NETLIFY_AUTH_TOKEN }}' -H 'Content-Type: application/zip' --data-binary output.zip https://api.netlify.com/api/v1/sites/${{ secrets.NETLIFY_SITE_ID }}/deploys"
